colaba/config/routes.rb
Colaba::Application.routes.draw do
  resources :subscriptions

  get "home/index"

  resources :merchants

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

colaba/app/models/merchant.rb
class Merchant < ActiveRecord::Base
  validates_presence_of :email
  validates_presence_of :login_id
  validates_presence_of :business_name
  validates_presence_of :business_phone
  validates_presence_of :business_type
  validates_presence_of :contact_name
  validates_format_of :contact_email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"
end

colaba/app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  # GET /merchants
  # GET /merchants.xml
  def index
    @merchants = Merchant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @merchants }
    end
  end

  # GET /merchants/1
  # GET /merchants/1.xml

  def show
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @merchant }
    end
  end

  # GET /merchants/new
  # GET /merchants/new.xml

  def new
    @merchant = Merchant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @merchant }
    end
  end

  # GET /merchants/1/edit

  def edit
    @merchant = Merchant.find(params[:id])
  end

  # POST /merchants
  # POST /merchants.xml

  def create
    @merchant = Merchant.new(params[:merchant])
      respond_to do |format|
        if @merchant.save
          session[:merchant_id] = @merchant.id
          format.html { redirect_to(:controller => 'subscriptions', :action =>"new", :notice => 'Merchant was successfully created.') }
          format.xml  { render :xml => @merchant, :status => :created, :location => @merchant }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @merchant.errors, :status => :unprocessable_entity }
        end
      end
  end

  # PUT /merchants/1
  # PUT /merchants/1.xml

  def update
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      if @merchant.update_attributes(params[:merchant])
        format.html { redirect_to(@merchant, :notice => 'Merchant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @merchant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.xml

  def destroy
    @merchant = Merchant.find(params[:id])
    @merchant.destroy

    respond_to do |format|
      format.html { redirect_to(merchants_url) }
      format.xml  { head :ok }
    end
  end
end

colaba/app/helpers/merchants_helper.rb
module MerchantsHelper
end

colaba/app/views/merchants/_form.html.erb
<%= form_for(@merchant) do |f| %>
  <% if @merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% @merchant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login_id %><br />
    <%= f.text_field :login_id, :maxlength => 15, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :business_name %><br />
    <%= f.text_field :business_name, :maxlength => 100, :size => 30%>
  </div>
  <div class="field">
    <%= f.label :business_phone %><br />
    <%= f.text_field :business_phone, :maxlength => 45, :size => 30%>
  </div>
  <div class="field">
    <%= f.label :business_type %><br />
    <%= f.text_field :business_type, :maxlength => 1%>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br />
    <%= f.text_field :contact_name, :maxlength => 100, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email, :maxlength => 100, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :tc_accepted %><br />
    <%= f.check_box :tc_accepted %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :create_at %><br />
    <%= f.datetime_select :create_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

colaba/app/views/merchants/edit.html.erb
<h1>Editing merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

colaba/app/views/merchants/index.html.erb
<h1>Listing merchants</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Login</th>
    <th>Business name</th>
    <th>Business phone</th>
    <th>Business type</th>
    <th>Contact name</th>
    <th>Contact email</th>
    <th>Tc accepted</th>
    <th>Is active</th>
    <th>Create at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @merchants.each do |merchant| %>
  <tr>
    <td><%= merchant.email %></td>
    <td><%= merchant.login_id %></td>
    <td><%= merchant.business_name %></td>
    <td><%= merchant.business_phone %></td>
    <td><%= merchant.business_type %></td>
    <td><%= merchant.contact_name %></td>
    <td><%= merchant.contact_email %></td>
    <td><%= merchant.tc_accepted %></td>
    <td><%= merchant.is_active %></td>
    <td><%= merchant.create_at %></td>
    <td><%= merchant.updated_at %></td>
    <td><%= link_to 'Show', merchant %></td>
    <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
    <td><%= link_to 'Destroy', merchant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Merchant', new_merchant_path %>

colaba/app/views/merchants/new.html.erb
<h1>New merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', merchants_path %>

colaba/app/views/merchants/payment.html.erb
<h1>New merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', merchants_path %>

colaba/app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @merchant.email %>
</p>

<p>
  <b>Login:</b>
  <%= @merchant.login_id %>
</p>

<p>
  <b>Business name:</b>
  <%= @merchant.business_name %>
</p>

<p>
  <b>Business phone:</b>
  <%= @merchant.business_phone %>
</p>

<p>
  <b>Business type:</b>
  <%= @merchant.business_type %>
</p>

<p>
  <b>Contact name:</b>
  <%= @merchant.contact_name %>
</p>

<p>
  <b>Contact email:</b>
  <%= @merchant.contact_email %>
</p>

<p>
  <b>Tc accepted:</b>
  <%= @merchant.tc_accepted %>
</p>

<p>
  <b>Is active:</b>
  <%= @merchant.is_active %>
</p>

<p>
  <b>Create at:</b>
  <%= @merchant.create_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @merchant.updated_at %>
</p>


<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>