colaba/config/routes.rb
Colaba::Application.routes.draw do
  resources :subscriptions

  get "home/index"

  resources :merchants

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

colaba/app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessor :billing_first_name, :billing_last_name,
          :credit_card_name, :credit_card_type, :credit_card_number, :credit_card_month, :credit_card_year,
          :credit_card_cvv_code, :credit_card_expire,
          :billing_first_name, :billing_last_name, :billing_country,
          :billing_company, :billing_address, :billing_address2, :billing_city,
          :billing_state, :billing_zipcode, :fee
  validates_presence_of :credit_card_number
  validates_presence_of :credit_card_name
  validates_presence_of :credit_card_type
  validates_presence_of :credit_card_month, :credit_card_year, :credit_card_cvv_code
  validates_presence_of :billing_first_name, :billing_last_name, :billing_country,
          :billing_address, :billing_city, :billing_state, :billing_zipcode


  validate :expiration_date_cannot_be_in_the_past
  def expiration_date_cannot_be_in_the_past
    errors.add(:credit_card_expire, "can't be in the past") if
      !credit_card_month.blank? and !credit_card_year.blank? and (Integer(credit_card_year) < Date.today.year() or (Integer(credit_card_year) ==Date.today.year() and Integer(credit_card_month) < Date.today.month()))
  end

end

colaba/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # GET /subscriptions
  # GET /subscriptions.xml
  def index
    @subscriptions = Subscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.xml

  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.xml

  def new
    @subscription = Subscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subscription }
    end
  end

  # GET /subscriptions/1/edit

  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.xml

  def create
    #create a random key to identify the new customer
    customer_id = Array.new(8/2) { rand(256) }.pack('C*').unpack('H*').first

    # The APP_CONFIG value comes from app_config.yml in the Config dir
    @subscription = Subscription.new(params[:subscription])

    #maybe this should be in the model?
    @subscription.plan_id = APP_CONFIG[:subscription_token]
    @subscription.customer_id = customer_id
    @subscription.sub_id = "#{Time.now.strftime("%Y%m%d%H%M%s")}"
    # First try to create the customer in BrainTree's vault, if successful then save the subscription record.
    # I'd like this process improved to so it's using error handling instead of flash messages
    @result = Braintree::Customer.create(
            :id => customer_id,
                    :first_name => params[:subscription]["billing_first_name"],
                    :last_name => params[:subscription]["billing_last_name"],
                    :company => params[:subscription]["billing_company"],
                    :credit_card => {
                            :cardholder_name => params[:subscription]["credit_card_name"],
                            :number => params[:subscription]["credit_card_number"],
                            :token => @subscription.sub_id,
                            :expiration_date => "#{params[:subscription]["credit_card_month"]}/#{params[:subscription]["credit_card_year"]}",
                            :cvv => params[:subscription]["credit_card_cvv_code"],
                            :billing_address => {
                                    :street_address => params[:subscription]["billing_address"],
                                    :extended_address =>params[:subscription]["billing_address2"],
                                    :locality => params[:subscription]["billing_city"],
                                    :region => params[:subscription]["billing_state"],
                                    :postal_code => params[:subscription]["billing_zipcode"],
                                    :country_code_numeric => params[:subscription]["billing_country"]
                            }
                    }
    )
    if @result.success?
      if  create_subscription( @subscription.sub_id, params[:subscription]["fee"])
        @merchant = Merchant.find(session[:merchant_id])
        @merchant.update_attributes(:customer_id => customer_id)
        # I removed all the respond_to code, I don't think I'll be using XML formating, shoudl all the respond_do code be removed?
        if @subscription.save
          redirect_to(:controller => 'subscriptions', :action => 'index', :notice => 'Subscription was successfully created.')
        else
          render :action => "new"
        end
      else
        render :action => "new"
      end
    else
      #was not able to create the customer, display error messages
      render :action => "new"
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.xml

  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to(@subscription, :notice => 'Subscription was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subscription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.xml

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to(subscriptions_url) }
      format.xml  { head :ok }
    end
  end

  private
  def create_subscription(sub_id, fee)
    logger.info "User has selected: #{APP_CONFIG[:subscription_token]}"
    result = Braintree::Subscription.create(
            :payment_method_token => sub_id,
                    :id => sub_id,
                    :plan_id => APP_CONFIG[:subscription_token],
                    :trial_duration => 0,
                    :trial_duration_unit => "month",
                    :price => fee
    )
    if result.success?
      return result.subscription.status
    else
      logger.info "ERROR CREATING SUBSCRIPTION: #{result.message}"
      flash[:error] = "We were not able to bill your credit card: #{result.message}"
      return false
    end
  end
end

colaba/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

colaba/app/views/subscriptions/_form.html.erb
<% if flash[:notice] %>
    <div style="font-family:'Trebuchet MS'; color:#FF0000; font-size:14px;">
        <%= flash[:notice] %>
    </div>
<% end %>
<%= form_for(@subscription) do |f| %>

    <% if @subscription.errors.any? == true and @result.success? !=false %>
        <div id="error_explanation">
            <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being
                saved:</h2>
            <ul>
                <% @subscription.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <% if @subscription.errors.any? == false and @result and  @result.success? !=true %>
        <div id="error_explanation">
            <h2><%= pluralize(@result.errors.count, "error") %> prohibited this subscription from being saved:</h2>
            <ul>
                <% @result.errors.each do |msg| %>
                    <li><%= msg.message %></li>
                <% end %>
                <% if @result.errors.count == 0 %>
                    <li><%= @result.message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <% if @subscription.errors.any? == true and  @result and @result.success? !=true %>
        <div id="error_explanation">
            <h2><%= pluralize(@result.errors.count + @subscription.errors.count, "error") %> prohibited this
                subscription from being saved:</h2>
            <ul>
                <% @subscription.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                <% @result.errors.each do |msg| %>
                    <li><%= msg.message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div id="billing_address">
        <h2>Billing Information</h2>
        <table>
            <tr>
                <td class="head" colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <td class="label">First Name</td>
                <td><%= f.text_field "billing_first_name" %></td>
            </tr>
            <tr>
                <td class="label">Last Name</td>
                <td><%= f.text_field "billing_last_name" %></td>
            </tr>
            <tr>
                <td class="label">Country</td>
                <td>
                    <%= select_tag 'subscription[billing_country]', options_for_select(Braintree::Address::CountryNames, "billing_country") %>
                 
                </td>
            </tr>
            <tr>
                <td class="label">Company <span>(optional)</span></td>
                <td><%= f.text_field "billing_company" %></td>
            </tr>
            <tr>
                <td class="label">Address 1</td>
                <td><%= f.text_field "billing_address" %></td>
            </tr>
            <tr>
                <td class="label">Address 2 <span>(optional)</span></td>
                <td><%= f.text_field "billing_address2" %></td>
            </tr>
            <tr>
                <td class="label">City</td>
                <td><%= f.text_field "billing_city" %></td>
            </tr>
            <tr>
                <td class="label">State/Province</td>
                <td><%= f.text_field "billing_state" %></td>
            </tr>
            <tr>
                <td class="label">Zip/Postal Code</td>
                <td><%= f.text_field "billing_zipcode" %></td>
            </tr>
            <tr>
                <td class="label">Fee</td>
                <td>
                    <select name="subscription[fee]" size="1">
                        <option value="50">50$</option>
                        <option value="100">100$</option>
                        <option value="150">150$</option>
                    </select>
                </td>
            </tr>
        </table>
    </div>

    <div id="payment_form">
        <h2>Your Payment Details</h2>
        <% options_for_year = Array.new -%>
        <% y = Date.today.year -%>
        <% 10.times do |n| -%>
            <% options_for_year.push n+y -%>
        <% end -%>
        <div id="payment_details">
            <table>
                <div class="field">
                    <tr>
                        <td class="label">Name on Card</td>
                        <td><%= f.text_field :credit_card_name %></td>
                    </tr>
                </div>
                <tr>
                    <td class="label">Card Type</td>
                    <td>
                        <%= f.select "credit_card_type", options_for_select([ "Visa", "MasterCard", "American Express", "Discover" ], @subscription.credit_card_type) %>
                    </td>
                </tr>
                <div class="field">
                    <tr>
                        <td class="label">Card Number</td>
                        <td><%= f.text_field :credit_card_number %></td>
                    </tr>
                </div>
                <tr>
                    <td class="label">Expiration</td>
                    <td>

                        <%
                           # maybe the credit card expiration should be handled using the date_select helper
                        -%>
                        <select name="subscription[credit_card_month]" size="1">
                            <option value="1">1 - Jan</option>
                            <option value="2">2 - Feb</option>
                            <option value="3">3 - Mar</option>
                            <option value="4">4 - Apr</option>
                            <option value="5">5 - May</option>
                            <option value="6">6 - Jun</option>
                            <option value="7">7 - Jul</option>
                            <option value="8">8 - Aug</option>
                            <option value="9">9 - Sep</option>
                            <option value="10">10 - Oct</option>
                            <option value="11">11 - Nov</option>
                            <option value="12">12 - Dec</option>
                        </select>
                        <select name="subscription[credit_card_year]" size="1">
                            <% y = Date.today.year -%>
                            <% 10.times do |n| -%>
                                <option value="<%= n+y -%>"><%= n+y -%></option>
                            <% end -%>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">CVV Code</td>
                    <td><%= f.text_field :credit_card_cvv_code, :size => 10 %> What's this?</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <p><%= f.submit "Submit Payment" -%></p>
                    </td>
                </tr>
            </table>
        </div>



        <div style="clear:both;"></div>

    </div>


<% end %>

colaba/app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

colaba/app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Plan</th>
    <th>Sub</th>
    <th>Cc token</th>
    <th>Merchant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= subscription.status %></td>
    <td><%= subscription.plan_id %></td>
    <td><%= subscription.sub_id %></td>
    <td><%= subscription.cc_token %></td>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

colaba/app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

colaba/app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @subscription.status %>
</p>

<p>
  <b>Plan:</b>
  <%= @subscription.plan_id %>
</p>

<p>
  <b>Sub:</b>
  <%= @subscription.sub_id %>
</p>

<p>
  <b>Cc token:</b>
  <%= @subscription.cc_token %>
</p>



<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>